import { Theme } from "./colors";

export function nolabels_layers(source: string, c: Theme): any[] {
  const casingVisibility = c.hasCasings ? "visible" : "none";
  return [
    {
      id: "background",
      type: "background",
      paint: {
        "background-color": c.background,
      },
    },
    {
      id: "earth",
      type: "fill",
      source: source,
      "source-layer": "earth",
      paint: {
        "fill-color": c.earth,
      },
    },
    {
      id: "landuse_park",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: [
        "any",
        ["in", "pmap:kind", "national_park", "park", "cemetery", "protected_area", "nature_reserve", "forest", "golf_course"],
      ],
      paint: {
        "fill-color": c.park,
      },
    },
    {
      id: "landuse_hospital",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["==", "pmap:kind", "hospital"]],
      paint: {
        "fill-color": c.hospital,
      },
    },
    {
      id: "landuse_industrial",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["==", "pmap:kind", "industrial"]],
      paint: {
        "fill-color": c.industrial,
      },
    },
    {
      id: "landuse_school",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["in", "pmap:kind", "school", "university", "college"]],
      paint: {
        "fill-color": c.school,
      },
    },
    {
      id: "landuse_beach",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["in", "pmap:kind", "beach"]],
      paint: {
        "fill-color": c.sand,
      },
    },
    {
      id: "landuse_zoo",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["in", "pmap:kind", "zoo"]],
      paint: {
        "fill-color": c.zoo,
      },
    },
    {
      id: "landuse_military",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["in", "pmap:kind", "military", "naval_base", "airfield"]],
      paint: {
        "fill-color": c.zoo,
      },
    },
    {
      id: "natural_wood",
      type: "fill",
      source: source,
      "source-layer": "natural",
      filter: [
        "any",
        ["in", "pmap:kind", "wood", "nature_reserve", "forest"],
      ],
      paint: {
        "fill-color": c.wood,
      },
    },
    {
      id: "landuse_pedestrian",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: ["any", ["==", "pmap:kind", "pedestrian"]],
      paint: {
        "fill-color": c.pedestrian,
      },
    },
    {
      id: "natural_scrub",
      type: "fill",
      source: source,
      "source-layer": "natural",
      filter: ["in", "pmap:kind", "scrub", "grassland", "grass"],
      paint: {
        "fill-color": c.scrub,
      },
    },
    {
      id: "natural_glacier",
      type: "fill",
      source: source,
      "source-layer": "natural",
      filter: ["==", "pmap:kind", "glacier"],
      paint: {
        "fill-color": c.glacier,
      },
    },
    {
      id: "natural_sand",
      type: "fill",
      source: source,
      "source-layer": "natural",
      filter: ["==", "pmap:kind", "sand"],
      paint: {
        "fill-color": c.sand,
      },
    },
    {
      id: "landuse_aerodrome",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: [
        "any",
        ["in", "pmap:kind", "aerodrome"],
      ],
      paint: {
        "fill-color": c.aerodrome,
      },
    },
    {
      id: "transit_runway",
      type: "line",
      source: source,
      "source-layer": "transit",
      filter: [
        "any",
        ["in", "pmap:kind_detail", "runway"],
      ],
      paint: {
        "line-color": c.runway,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          10,
          0,
          10.5,
          2,
          15,
          6,
        ],
      },
    },
    {
      id: "transit_taxiway",
      type: "line",
      source: source,
      "source-layer": "transit",
      min_zoom: 13,
      filter: [
        "any",
        ["in", "pmap:kind_detail", "taxiway"],
      ],
      paint: {
        "line-color": c.runway,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          1,
          15,
          6,
        ],
      },
    },
    {
      id: "landuse_runway",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      min_zoom: 14,
      filter: [
        "any",
        ["in", "pmap:kind_detail", "runway", "taxiway"],
      ],
      paint: {
        "fill-color": c.runway,
      },
    },
    {
      id: "water",
      type: "fill",
      source: source,
      "source-layer": "water",
      paint: {
        "fill-color": c.water,
      },
    },
    {
      id: "landuse_pier",
      type: "fill",
      source: source,
      "source-layer": "landuse",
      filter: [
        "any",
        ["==", "pmap:kind", "pier"],
      ],
      paint: {
        "fill-color": c.earth,
      },
    },
    {
      id: "roads_tunnels_other_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["<", "pmap:level", 0], ["in", "pmap:kind", "other", "path"]],
      paint: {
        "line-color": c.tunnel_other_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          14.5,
          0.5,
          20,
          12,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_tunnels_other",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["<", "pmap:level", 0], ["in", "pmap:kind", "other", "path"]],
      paint: {
        "line-color": c.tunnel_other,
        "line-dasharray": [1, 1],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          14.5,
          0.5,
          20,
          12,
        ],
      },
    },
    {
      id: "roads_tunnels_minor_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["<", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
      ],
      paint: {
        "line-color": c.tunnel_minor_casing,
        "line-dasharray": [3, 2],
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_tunnels_minor",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["<", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
      ],
      paint: {
        "line-color": c.tunnel_minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_tunnels_medium_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["<", "pmap:level", 0],
        ["==", "pmap:kind", "medium_road"],
      ],
      paint: {
        "line-color": c.tunnel_medium_casing,
        "line-dasharray": [3, 2],
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          20,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          10,
          0,
          10.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_tunnels_medium",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["<", "pmap:level", 0],
        ["==", "pmap:kind", "medium_road"],
      ],
      paint: {
        "line-color": c.tunnel_medium,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_tunnels_major_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["<", "pmap:level", 0],
        ["==", "pmap:kind", "major_road"],
      ],
      paint: {
        "line-color": c.tunnel_major_casing,
        "line-dasharray": [3, 2],
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          19,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          9,
          0,
          9.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_tunnels_major",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["<", "pmap:level", 0],
        ["==", "pmap:kind", "major_road"],
      ],
      paint: {
        "line-color": c.tunnel_major,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          19,
          32,
        ],
      },
    },
    {
      id: "roads_tunnels_highway_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["<", "pmap:level", 0], ["==", "pmap:kind", "highway"], ["!=", "pmap:link", 1]],
      paint: {
        "line-color": c.tunnel_highway_casing,
        "line-dasharray": [3, 2],
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_tunnels_highway",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["<", "pmap:level", 0], ["==", "pmap:kind", "highway"], ["!=", "pmap:link", 1]],
      paint: {
        "line-color": c.tunnel_highway,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          32,
        ],
      },
    },
    {
      id: "physical_line_stream",
      type: "line",
      source: source,
      "source-layer": "physical_line",
      min_zoom: 14,
      filter: ["all", ["in", "pmap:kind", "stream"]],
      paint: {
        "line-color": c.water,
        "line-width": 0.5,
      },
    },
    {
      id: "physical_line_river",
      type: "line",
      source: source,
      "source-layer": "physical_line",
      min_zoom: 9,
      filter: ["all", ["in", "pmap:kind", "river"]],
      paint: {
        "line-color": c.water,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          9,
          0,
          9.5,
          1.0,
          18,
          12,
        ],
      },
    },
    {
      id: "buildings",
      type: "fill-extrusion",
      source: source,
      "source-layer": "buildings",
      paint: {
        "fill-extrusion-color": c.buildings,
        "fill-extrusion-height": ["to-number", ["get", "height"]],
        "fill-extrusion-opacity": 0.5,
      },
    },
    {
      id: "roads_other",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["==", "pmap:level", 0], ["in", "pmap:kind", "other", "path"]],
      paint: {
        "line-color": c.other,
        "line-dasharray": [2, 1],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          14.5,
          0.5,
          20,
          12,
        ],
      },
    },
    {
      id: "roads_link_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      minzoom: 13,
      filter: [
        "all",
        ["==", "pmap:link", 1],
      ],
      paint: {
        "line-color": c.minor_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          0.5,
          20,
          24,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          2,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_minor_service_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      minzoom: 13,
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
        ["==", "pmap:kind_detail", "service"],
      ],
      paint: {
        "line-color": c.minor_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          0.25,
          20,
          24,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          0.8,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_minor_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
        ["!=", "pmap:kind_detail", "service"],
      ],
      paint: {
        "line-color": c.minor_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          24,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          .6,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "transit_pier",
      type: "line",
      source: source,
      "source-layer": "transit",
      filter: [
        "any",
        ["==", "pmap:kind", "pier"],
      ],
      paint: {
        "line-color": c.minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          16,
        ],
      },
    },
    {
      id: "roads_link",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:link", 1],
      ],
      paint: {
        "line-color": c.minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          1,
          20,
          24,
        ],
      },
    },
    {
      id: "roads_minor_service",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
        ["==", "pmap:kind_detail", "service"],
      ],
      paint: {
        "line-color": c.minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          13,
          0,
          13.5,
          0.25,
          20,
          24,
        ],
      },
    },
    {
      id: "roads_minor",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
        ["!=", "pmap:kind_detail", "service"],
      ],
      paint: {
        "line-color": c.minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_medium_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "medium_road"],
      ],
      paint: {
        "line-color": c.medium_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          20,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          10,
          0,
          10.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_medium",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "medium_road"],
      ],
      paint: {
        "line-color": c.medium,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_major_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "major_road"],
      ],
      paint: {
        "line-color": c.major_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          19,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          9,
          0,
          9.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_major",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        ["==", "pmap:level", 0],
        ["==", "pmap:kind", "major_road"],
      ],
      paint: {
        "line-color": c.major,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          6,
          0,
          6.5,
          0.5,
          19,
          32,
        ],
      },
    },
    {
      id: "roads_highway_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["==", "pmap:level", 0], ["==", "pmap:kind", "highway"], ["!=", "pmap:link", 1]],
      paint: {
        "line-color": c.highway_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_highway",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", ["==", "pmap:level", 0], ["==", "pmap:kind", "highway"], ["!=", "pmap:link", 1]],
      paint: {
        "line-color": c.highway,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          32,
        ],
      },
    },
    {
      id: "transit_railway",
      type: "line",
      source: source,
      "source-layer": "transit",
      filter: ["all", ["==", "pmap:kind", "rail"]],
      paint: {
        "line-color": c.railway,
        "line-width": 2,
      },
    },
    {
      id: "transit_railway_tracks",
      type: "line",
      source: source,
      "source-layer": "transit",
      filter: ["all", ["==", "pmap:kind", "rail"]],
      paint: {
        "line-color": c.railway_tracks,
        "line-width": 0.8,
        "line-dasharray": [6, 10],
      },
    },
    {
      id: "boundaries",
      type: "line",
      source: source,
      "source-layer": "boundaries",
      paint: {
        "line-color": c.boundaries,
        "line-width": 0.5,
        "line-dasharray": [3, 2],
      },
    },
    {
      id: "roads_bridges_other_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", [">", "pmap:level", 0], ["in", "pmap:kind", "other", "path"]],
      paint: {
        "line-color": c.bridges_other_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          14.5,
          0.5,
          20,
          12,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_bridges_other",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", [">", "pmap:level", 0], ["in", "pmap:kind", "other", "path"]],
      paint: {
        "line-color": c.bridges_other,
        "line-dasharray": [2, 1],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          14,
          0,
          14.5,
          0.5,
          20,
          12,
        ],
      },
    },
    {
      id: "roads_bridges_link_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:link", 1],
      ],
      paint: {
        "line-color": c.bridges_minor_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          1,
          20,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          2,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_bridges_minor_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
      ],
      paint: {
        "line-color": c.bridges_minor_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_bridges_link",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:link", 1],
      ],
      paint: {
        "line-color": c.bridges_minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          1,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_bridges_minor",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:kind", "minor_road"],
      ],
      paint: {
        "line-color": c.bridges_minor,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0,
          12.5,
          0.5,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_bridges_medium_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:kind", "medium_road"],
      ],
      paint: {
        "line-color": c.bridges_medium_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          20,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          10,
          0,
          10.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_bridges_medium",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:kind", "medium_road"],
      ],
      paint: {
        "line-color": c.bridges_medium,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          20,
          32,
        ],
      },
    },
    {
      id: "roads_bridges_major_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:kind", "major_road"],
      ],
      paint: {
        "line-color": c.bridges_major_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          19,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          9,
          0,
          9.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_bridges_major",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: [
        "all",
        [">", "pmap:level", 0],
        ["==", "pmap:kind", "major_road"],
      ],
      paint: {
        "line-color": c.bridges_major,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          0.5,
          19,
          32,
        ],
      },
    },
    {
      id: "roads_bridges_highway_casing",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", [">", "pmap:level", 0], ["==", "pmap:kind", "highway"], ["!=", "pmap:link", 1]],
      paint: {
        "line-color": c.bridges_highway_casing,
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          32,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          7,
          0,
          7.5,
          1,
        ],
      },
      layout: {
        visibility: casingVisibility,
      },
    },
    {
      id: "roads_bridges_highway",
      type: "line",
      source: source,
      "source-layer": "roads",
      filter: ["all", [">", "pmap:level", 0], ["==", "pmap:kind", "highway"], ["!=", "pmap:link", 1]],
      paint: {
        "line-color": c.bridges_highway,
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          3,
          0,
          3.5,
          0.5,
          18,
          32,
        ],
      },
    },
  ];
}

export function labels_layers(source: string, c: Theme): any[] {
  return [
    {
      id: "physical_line_waterway_label",
      type: "symbol",
      source: source,
      "source-layer": "physical_line",
      minzoom: 13,
      filter: ["all", ["in", "pmap:kind", "river", "stream"]],
      layout: {
        "symbol-placement": "line",
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 12,
        "text-letter-spacing": 0.3,
      },
      paint: {
        "text-color": c.waterway_label,
        "text-halo-color": c.waterway_label_halo,
        "text-halo-width": 2,
      },
    },
    {
      id: "physical_point_peak",
      type: "symbol",
      source: source,
      "source-layer": "physical_point",
      filter: ["any", ["==", "pmap:kind", "peak"]],
      layout: {
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 11,
        "text-max-width": 9
      },
      paint: {
        "text-color": c.peak_label,
        "text-halo-color": c.peak_label_halo,
        "text-halo-width": 1.5,
      },
    },
    {
      id: "roads_labels_minor",
      type: "symbol",
      source: source,
      "source-layer": "roads",
      minzoom: 15,
      filter: ["any", ["in", "pmap:kind", "minor_road", "other", "path"]],
      layout: {
        "symbol-placement": "line",
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 12,
      },
      paint: {
        "text-color": c.roads_label,
        "text-halo-color": c.roads_label_halo,
        "text-halo-width": 2,
      },
    },
    {
      id: "pois_high_zooms",
      type: "symbol",
      source: source,
      minzoom: 15,
      "source-layer": "pois",
      "filter": ["any", [">=", ["get", "pmap:min_zoom"], 13]],
      layout: {
        "symbol-sort-key": ["get", "pmap:min_zoom"],
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 11,
        "text-max-width": 9,
        "icon-padding": ["interpolate", ["linear"],
          ["zoom"], 0, 2, 14, 2, 16, 20, 17, 2, 22, 2
        ],
      },
      paint: {
        "text-color": c.subplace_label,
        "text-halo-color": c.subplace_label_halo,
        "text-halo-width": 1.5,
      },
    },
    {
      id: "mask",
      type: "fill",
      source: source,
      "source-layer": "mask",
      paint: {
        "fill-color": c.background,
      },
    },
    {
      id: "physical_point_ocean",
      type: "symbol",
      source: source,
      "source-layer": "physical_point",
      filter: ["any", ["in", "pmap:kind", "sea", "ocean", "lake", "water", "bay", "strait", "fjord"]],
      layout: {
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 11,
        "text-letter-spacing": 0.1,
        "text-max-width": 9
      },
      paint: {
        "text-color": c.ocean_label,
        "text-halo-color": c.ocean_label_halo,
        "text-halo-width": 1,
      },
    },
    {
      id: "roads_labels_major",
      type: "symbol",
      source: source,
      "source-layer": "roads",
      filter: ["any", ["in", "pmap:kind", "highway", "major_road", "medium_road"]],
      layout: {
        "symbol-placement": "line",
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 12,
      },
      paint: {
        "text-color": c.roads_label,
        "text-halo-color": c.roads_label_halo,
        "text-halo-width": 2,
      },
    },
    {
      id: "places_subplace",
      type: "symbol",
      source: source,
      "source-layer": "places",
      filter: ["==", "pmap:kind", "neighbourhood"],
      layout: {
        "symbol-sort-key": ["get", "pmap:min_zoom"],
        "text-field": "{name}",
        "text-font": ["NotoSans-Regular"],
        "text-max-width": 7,
        "text-padding": 4,
        "text-size": {
          base: 1.2,
          stops: [
            [11, 10],
            [14, 12],
          ],
        },
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": c.subplace_label,
        "text-halo-color": c.subplace_label_halo,
        "text-halo-width": 1.0,
      },
    },
    {
      id: "pois_important",
      type: "symbol",
      source: source,
      "source-layer": "pois",
      "filter": ["any", ["<", ["get", "pmap:min_zoom"], 13]],
      layout: {
        "symbol-sort-key": ["get", "pmap:min_zoom"],
        "text-font": ["NotoSans-Regular"],
        "text-field": ["get", "name"],
        "text-size": 11,
        "text-max-width": 9,
        "icon-padding": ["interpolate", ["linear"],
          ["zoom"], 0, 2, 14, 2, 16, 20, 17, 2, 22, 2
        ],
      },
      paint: {
        "text-color": c.subplace_label,
        "text-halo-color": c.subplace_label_halo,
        "text-halo-width": 1.5,
      },
    },
    {
      id: "places_locality_circle",
      type: "circle",
      source: source,
      "source-layer": "places",
      filter: ["==", "pmap:kind", "locality"],
      paint: {
        "circle-radius": 2,
        "circle-stroke-width": 2,
        "circle-stroke-color": c.city_circle_stroke,
        "circle-color": c.city_circle,
      },
      maxzoom: 8,
    },
    {
      id: "places_locality",
      type: "symbol",
      source: source,
      "source-layer": "places",
      filter: ["==", "pmap:kind", "locality"],
      layout: {
        "symbol-sort-key": ["to-number", ["concat", ["get", "pmap:min_zoom"],
              ["+", 1, ["/", 1, ["get", "pmap:population_rank"]]]
            ]],
        "text-field": "{name}",
        "text-font": ["NotoSans-Regular"],
        "text-size": ["interpolate", ["linear"],
          ["zoom"],
          4, ["case", ["<", ["get", "pmap:population_rank"], 10], 11,
                      [">=", ["get", "pmap:population_rank"], 10], 12, 0],
          6.99, ["case", ["<", ["get", "pmap:population_rank"], 9], 11,
                         [">=", ["get", "pmap:population_rank"], 9], 13, 0],
          15,   ["case", ["<", ["get", "pmap:population_rank"], 8], 12,
                         [">=", ["get", "pmap:population_rank"], 8], 14, 0
          ]
        ],
        "icon-padding": ["interpolate", ["linear"],
          ["zoom"], 0, 2, 8, 4, 10, 8, 12, 6, 22, 2
        ],
        "text-anchor": {
          stops: [
            [7, "left"],
            [8, "center"],
          ],
        },
        "text-radial-offset": 0.2,
      },
      paint: {
        "text-color": c.city_label,
        "text-halo-color": c.city_label_halo,
        "text-halo-width": 1,
      },
    },
    {
      id: "places_region",
      type: "symbol",
      source: source,
      "source-layer": "places",
      filter: ["==", "pmap:kind", "region"],
      layout: {
        "symbol-sort-key": ["get", "pmap:min_zoom"],
        "text-field": "{name}",
        "text-font": ["NotoSans-Regular"],
        "text-size": 12,
        "text-radial-offset": 0.2,
        "text-anchor": "center",
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": c.state_label,
        "text-halo-color": c.state_label_halo,
        "text-halo-width": 0.5,
      },
    },
    {
      id: "places_country",
      type: "symbol",
      source: source,
      "source-layer": "places",
      filter: ["==", "pmap:kind", "country"],
      layout: {
        "symbol-sort-key": ["get", "pmap:min_zoom"],
        "text-field": "{name}",
        "text-font": ["NotoSans-Bold"],
        "text-size": ["interpolate", ["linear"],
          ["zoom"],
          2, ["case", ["<", ["get", "pmap:population_rank"], 10], 11,
                      [">=", ["get", "pmap:population_rank"], 10], 12, 0],
          6, ["case", ["<", ["get", "pmap:population_rank"], 8], 11,
                         [">=", ["get", "pmap:population_rank"], 8], 14, 0],
          8,   ["case", ["<", ["get", "pmap:population_rank"], 7], 12,
                         [">=", ["get", "pmap:population_rank"], 7], 20, 0
          ]
        ],
        "icon-padding": ["interpolate", ["linear"],
          ["zoom"], 0, 2, 14, 2, 16, 20, 17, 2, 22, 2
        ],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": c.country_label,
        "text-halo-color": c.country_label_halo,
        "text-halo-width": 1.0,
      },
    },
  ];
}
