export interface Theme {
    hasCasings: boolean;
    background: string;
    earth: string;
    park: string;
    hospital: string;
    industrial: string;
    school: string;
    wood: string;
    pedestrian: string;
    scrub: string;
    glacier: string;
    sand: string;
    aerodrome: string;
    runway: string;
    water: string;
    tunnel_other_casing: string;
    tunnel_other: string;
    tunnel_minor_casing: string;
    tunnel_minor: string;
    tunnel_medium_casing: string;
    tunnel_medium: string;
    tunnel_major_casing: string;
    tunnel_major: string;
    tunnel_highway_casing: string;
    tunnel_highway: string;
    buildings: string;
    other: string;
    minor_casing: string;
    minor: string;
    medium_casing: string;
    medium: string;
    major_casing: string;
    major: string;
    highway_casing: string;
    highway: string;
    railway: string;
    railway_tracks: string;
    boundaries: string;
    waterway_label_halo: string;
    waterway_label: string;
    bridges_other_casing: string;
    bridges_other: string;
    bridges_minor_casing: string;
    bridges_minor: string;
    bridges_medium_casing: string;
    bridges_medium: string;
    bridges_major_casing: string;
    bridges_major: string;
    bridges_highway_casing: string;
    bridges_highway: string;
    roads_label: string;
    roads_label_halo: string;
    ocean_label: string;
    ocean_label_halo: string;
    peak_label: string;
    peak_label_halo: string;
    subplace_label: string;
    subplace_label_halo: string;
    city_circle: string;
    city_circle_stroke: string;
    city_label: string;
    city_label_halo: string;
    state_label: string;
    state_label_halo: string;
    country_label: string;
    country_label_halo: string;
}

export const LIGHT: Theme = {
    hasCasings: true,
    background: "#dddddd",
    earth: "#e7f1ee",
    park: "#c2f7d1",
    hospital: "#ffeae8",
    industrial: "#f8ffed",
    school: "#f2fef9",
    wood: "#eafbe9",
    pedestrian: "#eef0f0",
    scrub: "rgb(219,239,209)",
    glacier: "white",
    sand: "#eff5e7",
    aerodrome: "#dbe7e7",
    runway: "#d1d9d9",
    water: "#a4cae1",
    tunnel_other_casing: "#ffffff",
    tunnel_other: "#f7f7f7",
    tunnel_minor_casing: "#e2e2e2",
    tunnel_minor: "#ebebeb",
    tunnel_medium_casing: "#e1e1e1",
    tunnel_medium: "#ebebeb",
    tunnel_major_casing: "#e3cfd3",
    tunnel_major: "#ebebeb",
    tunnel_highway_casing: "#ebcea2",
    tunnel_highway: "#ebebeb",
    buildings: "#cbcece",
    other: "#ffffff",
    minor_casing: "#e2e2e2",
    minor: "white",
    medium_casing: "#e1e1e1",
    medium: "#ffffff",
    major_casing: "#e3cfd3",
    major: "#ffffff",
    highway_casing: "#ebcea2",
    highway: "#fefffc",
    railway: "#b3bcc9",
    railway_tracks: "#ffffff",
    boundaries: "#5c4a6b",
    waterway_label_halo: "white",
    waterway_label: "#a4cae1",
    bridges_other_casing: "#ffffff",
    bridges_other: "#ffffff",
    bridges_minor_casing: "#e2e2e2",
    bridges_minor: "white",
    bridges_medium_casing: "#e1e1e1",
    bridges_medium: "#ffffff",
    bridges_major_casing: "#e3cfd3",
    bridges_major: "#ffffff",
    bridges_highway_casing: "#ebcea2",
    bridges_highway: "#fefffc",
    roads_label: "#91888b",
    roads_label_halo: "white",
    ocean_label: "white",
    ocean_label_halo: "#a4cae1",
    peak_label: "#61bb5b",
    peak_label_halo: "#ffffff",
    subplace_label: "#757d91",
    subplace_label_halo: "white",
    city_circle: "#666666",
    city_circle_stroke: "white",
    city_label: "#787878",
    city_label_halo: "white",
    state_label: "#bdbdbd",
    state_label_halo: "White",
    country_label: "#9590aa",
    country_label_halo: "white",
};

export const DARK: Theme = {
    hasCasings: true,
    background: "#dddddd",
    earth: "#151515",
    park: "#1d3e2e",
    hospital: "#2e2226",
    industrial: "#20201e",
    school: "#193a3c",
    wood: "#212e25",
    pedestrian: "#1a1a1a",
    scrub: "#27362a",
    glacier: "#1c1c1c",
    sand: "#374238",
    aerodrome: "#000000",
    runway: "#000000",
    water: "#1e293b",
    tunnel_other_casing: "#ffffff",
    tunnel_other: "#000000",
    tunnel_minor_casing: "#ffffff",
    tunnel_minor: "#000000",
    tunnel_medium_casing: "#ffffff",
    tunnel_medium: "#000000",
    tunnel_major_casing: "#ffffff",
    tunnel_major: "#000000",
    tunnel_highway_casing: "#ffffff",
    tunnel_highway: "#000000",
    buildings: "#393f43",
    other: "#000000",
    minor_casing: "#222222",
    minor: "#000000",
    medium_casing: "#222222",
    medium: "#282828",
    major_casing: "#222222",
    major: "#2f2f2f",
    highway_casing: "#222222",
    highway: "#3b3b3b",
    railway: "#bbbbbb",
    railway_tracks: "#000000",
    boundaries: "#6b1001",
    waterway_label_halo: "#000000",
    waterway_label: "#ffffff",
    bridges_other_casing: "#ffffff",
    bridges_other: "#000000",
    bridges_minor_casing: "#ffffff",
    bridges_minor: "#000000",
    bridges_medium_casing: "#ffffff",
    bridges_medium: "#000000",
    bridges_major_casing: "#ffffff",
    bridges_major: "#000000",
    bridges_highway_casing: "#ffffff",
    bridges_highway: "#000000",
    roads_label: "#7a7a7a",
    roads_label_halo: "#000000",
    ocean_label: "#ffffff",
    ocean_label_halo: "#000000",
    peak_label: "#ffffff",
    peak_label_halo: "#000000",
    subplace_label: "#8e8e8e",
    subplace_label_halo: "#000000",
    city_circle: "#ffffff",
    city_circle_stroke: "#000000",
    city_label: "#ffffff",
    city_label_halo: "#000000",
    state_label: "#ffffff",
    state_label_halo: "#000000",
    country_label: "#ffffff",
    country_label_halo: "#000000",
};

export const WHITE: Theme = {
    hasCasings: false,
    background: "#ffffff",
    earth: "#ffffff",
    park: "#ffffff",
    hospital: "#ffffff",
    industrial: "#ffffff",
    school: "#ffffff",
    wood: "#ffffff",
    pedestrian: "#ffffff",
    scrub: "#ffffff",
    glacier: "#ffffff",
    sand: "#ffffff",
    aerodrome: "#ffffff",
    runway: "#ffffff",
    water: "#eeeeee",
    tunnel_other_casing: "#ff00ff",
    tunnel_other: "#ffffff",
    tunnel_minor_casing: "#ff00ff",
    tunnel_minor: "#ffffff",
    tunnel_medium_casing: "#ff00ff",
    tunnel_medium: "#ffffff",
    tunnel_major_casing: "#ff00ff",
    tunnel_major: "#ffffff",
    tunnel_highway_casing: "#ff00ff",
    tunnel_highway: "#ffffff",
    buildings: "#ffffff",
    other: "#ffffff",
    minor_casing: "#ff00ff",
    minor: "#ffffff",
    medium_casing: "#ff00ff",
    medium: "#ffffff",
    major_casing: "#ff00ff",
    major: "#ffffff",
    highway_casing: "#ff00ff",
    highway: "#ffffff",
    railway: "#bbbbbb",
    railway_tracks: "#ffffff",
    boundaries: "#000000",
    waterway_label_halo: "#ffffff",
    waterway_label: "#000000",
    bridges_other_casing: "#ff00ff",
    bridges_other: "#ffffff",
    bridges_minor_casing: "#ff00ff",
    bridges_minor: "#ffffff",
    bridges_medium_casing: "#ff00ff",
    bridges_medium: "#ffffff",
    bridges_major_casing: "#ff00ff",
    bridges_major: "#ffffff",
    bridges_highway_casing: "#ff00ff",
    bridges_highway: "#ffffff",
    roads_label: "#000000",
    roads_label_halo: "#ffffff",
    ocean_label: "#000000",
    ocean_label_halo: "#ffffff",
    peak_label: "#000000",
    peak_label_halo: "#ffffff",
    subplace_label: "#000000",
    subplace_label_halo: "#ffffff",
    city_circle: "#000000",
    city_circle_stroke: "#ffffff",
    city_label: "#000000",
    city_label_halo: "#ffffff",
    state_label: "#000000",
    state_label_halo: "#ffffff",
    country_label: "#000000",
    country_label_halo: "#ffffff",
};

export const BLACK: Theme = {
    hasCasings: false,
    background: "#000000",
    earth: "#000000",
    park: "#000000",
    hospital: "#000000",
    industrial: "#000000",
    school: "#000000",
    wood: "#000000",
    pedestrian: "#000000",
    scrub: "#000000",
    glacier: "#000000",
    sand: "#000000",
    aerodrome: "#000000",
    runway: "#000000",
    water: "#222222",
    tunnel_other_casing: "#ff00ff",
    tunnel_other: "#000000",
    tunnel_minor_casing: "#ff00ff",
    tunnel_minor: "#000000",
    tunnel_medium_casing: "#ff00ff",
    tunnel_medium: "#000000",
    tunnel_major_casing: "#ff00ff",
    tunnel_major: "#000000",
    tunnel_highway_casing: "#ff00ff",
    tunnel_highway: "#000000",
    buildings: "#000000",
    other: "#000000",
    minor_casing: "#ff00ff",
    minor: "#000000",
    medium_casing: "#ff00ff",
    medium: "#000000",
    major_casing: "#ff00ff",
    major: "#000000",
    highway_casing: "#ff00ff",
    highway: "#000000",
    railway: "#bbbbbb",
    railway_tracks: "#000000",
    boundaries: "#ffffff",
    waterway_label_halo: "#ffffff",
    waterway_label: "#000000",
    bridges_other_casing: "#ff00ff",
    bridges_other: "#000000",
    bridges_minor_casing: "#ff00ff",
    bridges_minor: "#000000",
    bridges_medium_casing: "#ff00ff",
    bridges_medium: "#000000",
    bridges_major_casing: "#ff00ff",
    bridges_major: "#000000",
    bridges_highway_casing: "#ff00ff",
    bridges_highway: "#000000",
    roads_label: "#ffffff",
    roads_label_halo: "#000000",
    ocean_label: "#ffffff",
    ocean_label_halo: "#000000",
    peak_label: "#ffffff",
    peak_label_halo: "#000000",
    subplace_label: "#ffffff",
    subplace_label_halo: "#000000",
    city_circle: "#ffffff",
    city_circle_stroke: "#000000",
    city_label: "#ffffff",
    city_label_halo: "#000000",
    state_label: "#ffffff",
    state_label_halo: "#000000",
    country_label: "#ffffff",
    country_label_halo: "#000000",
};

export const GRAYSCALE: Theme = {
    hasCasings: false,
    background: "#eee",
    earth: "#eee",
    park: "#e8e8e8",
    hospital: "#e8e8e8",
    industrial: "#e8e8e8",
    school: "#e8e8e8",
    wood: "#e8e8e8",
    pedestrian: "#e8e8e8",
    scrub: "#e8e8e8",
    glacier: "#e8e8e8",
    sand: "#e8e8e8",
    aerodrome: "#e8e8e8",
    runway: "#e8e8e8",
    water: "#ddd",
    tunnel_other_casing: "#ff00ff",
    tunnel_other: "#ffffff",
    tunnel_minor_casing: "#ff00ff",
    tunnel_minor: "#ffffff",
    tunnel_medium_casing: "#ff00ff",
    tunnel_medium: "#ffffff",
    tunnel_major_casing: "#ff00ff",
    tunnel_major: "#ffffff",
    tunnel_highway_casing: "#ff00ff",
    tunnel_highway: "#ffffff",
    buildings: "#ffffff",
    other: "#fff",
    minor_casing: "#ff00ff",
    minor: "#fff",
    medium_casing: "#ff00ff",
    medium: "#fff",
    major_casing: "#ff00ff",
    major: "#fff",
    highway_casing: "#ff00ff",
    highway: "#fff",
    railway: "#fff",
    railway_tracks: "#eee",
    boundaries: "#666",
    waterway_label_halo: "#bbbbbb",
    waterway_label: "#ffffff",
    bridges_other_casing: "#ff00ff",
    bridges_other: "#ffffff",
    bridges_minor_casing: "#ff00ff",
    bridges_minor: "#ffffff",
    bridges_medium_casing: "#ff00ff",
    bridges_medium: "#ffffff",
    bridges_major_casing: "#ff00ff",
    bridges_major: "#ffffff",
    bridges_highway_casing: "#ff00ff",
    bridges_highway: "#ffffff",
    roads_label: "#888",
    roads_label_halo: "#ffffff",
    ocean_label: "#666",
    ocean_label_halo: "#ffffff",
    peak_label: "#000000",
    peak_label_halo: "#ffffff",
    subplace_label: "#888",
    subplace_label_halo: "#ffffff",
    city_circle: "#666",
    city_circle_stroke: "#ffffff",
    city_label: "#888",
    city_label_halo: "#ffffff",
    state_label: "#888",
    state_label_halo: "#ffffff",
    country_label: "#888",
    country_label_halo: "#ffffff",
};

export default {
    light: LIGHT,
    dark: DARK,
    white: WHITE,
    black: BLACK,
    grayscale: GRAYSCALE,
};
