#!/usr/bin/env python3
import json
import argparse

parser = argparse.ArgumentParser(description='Generate a MapboxGL style from a template and parameters.')
parser.add_argument('template', type=str)
parser.add_argument('params', nargs='?', type=str)
parser.add_argument('-key', type=str)
args = parser.parse_args()

with open(args.template,'r') as template:
    j = json.loads(template.read())

    if args.key:
        j['sources']['protomaps']['tiles'][0] = j['sources']['protomaps']['tiles'][0] + "?key=" + args.key

    if args.params:
        j['name'] = args.params
        with open(args.params,'r') as params:
            for line in params.readlines():
                if not line.strip() or line.startswith('#'):
                    continue
                target, value = [s.strip() for s in line.split('=')]
                parts = target.split('.')
                ref = [l for l in j['layers'] if l['id'] == parts[0]][0]
                for p in parts[1:-1]:
                    ref = ref[p]
                if parts[-1] not in ref:
                    print(target + " does not exist")
                    exit(1)

                ref[parts[-1]] = value

    print(json.dumps(j,indent=4))
