all:
	./target/release/spritegen refill.svg themes/light.json dist/light
	./target/release/spritegen refill.svg themes/dark.json dist/dark
	./target/release/spritegen refill.svg themes/white.json dist/white
	./target/release/spritegen refill.svg themes/grayscale.json dist/grayscale
	./target/release/spritegen refill.svg themes/black.json dist/black