all:
	./target/release/spritegen refill.svg flavors/light.json dist/light
	./target/release/spritegen refill.svg flavors/dark.json dist/dark
	./target/release/spritegen refill.svg flavors/white.json dist/white
	./target/release/spritegen refill.svg flavors/grayscale.json dist/grayscale
	./target/release/spritegen refill.svg flavors/black.json dist/black