# https://github.com/onthegomap/planetiler/blob/main/.github/cache-sources-action/action.yml
name: 'Cache tiles/data/sources'
description: 'Save/restore data/sources cache'
inputs:
  basedir:
    description: 'Base dir for computing file hash'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Get Date
      id: get-data
      run: |
        echo "::set-output name=date::$(date -u "+%Y-%m-%d")"
      shell: bash
      working-directory: ${{ inputs.basedir }}
    - uses: actions/cache@v2
      with:
        path: tiles/data/sources
        key: data-sources-${{ steps.get-data.outputs.date }}