# Derived from planetiler (Apache License)
# https://github.com/onthegomap/planetiler/blob/main/.github/workflows/maven.yml

name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_lint:
    name: Run unit tests and check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
    - name: Run unit tests
      working-directory: tiles
      run: mvn --batch-mode -no-transfer-progress test
    - name: Ensure code formatted with mvn spotless:apply
      working-directory: tiles
      run: mvn spotless:check
    - name: Check for required version bump
      if: github.ref_name != 'main'
      run: |
        git fetch origin main:main
        .github/workflows/check-version-bump.sh
