# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # When spotless:apply fails, the error message is a bit cryptic, so try to make it obvious that
  # is the problem by putting the check into a standalone job
  lint:
    name: Check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
    - name: Ensure code formatted with mvn spotless:apply
      working-directory: tiles
      run: mvn -DskipTests --batch-mode -no-transfer-progress spotless:check

  build:
    name: Java ${{ matrix.jdk }} / ${{ matrix.os }} ${{ matrix.args }}
    # Wait until after we check that you ran mvn spotless:apply, otherwise will fail with a cryptic error message
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 17 ]
        include:
        - os: ubuntu-latest
          jdk: 17
          args: "-DargLine='-Duser.language=fr -Duser.country=FR'"
        - os: ubuntu-latest
          jdk: 18
        - os: ubuntu-latest
          jdk: 19
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    # Skip spotless since that gets checked in a separate task
    - name: Build with mvn (linux/mac)
      working-directory: tiles
      if: ${{ !contains(matrix.os, 'windows') }}
      run: mvn ${{matrix.args}} -Dspotless.check.skip --batch-mode -no-transfer-progress package verify jib:buildTar --file pom.xml
    - name: Build with mvn.cmd (windows)
      working-directory: tiles
      if: ${{ contains(matrix.os, 'windows') }}
      run: mvn.cmd ${{matrix.args}} -Dspotless.check.skip --batch-mode -no-transfer-progress package verify jib:buildTar --file pom.xml
      shell: cmd
