# Derived from planetiler (Apache License)
# https://github.com/onthegomap/planetiler/blob/main/.github/workflows/maven.yml

name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_lint:
    name: Run unit tests and check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
    - name: Run unit tests
      working-directory: tiles
      run: mvn --batch-mode -no-transfer-progress test
    - name: Ensure code formatted with mvn spotless:apply
      working-directory: tiles
      run: mvn spotless:check
    - name: Check styles
      run: npm install && npx tsc --noEmit && npm test && npm run prettier-check
      working-directory: styles
    - run: python .github/check_examples.py