# Derived from planetiler (Apache License)
# https://github.com/onthegomap/planetiler/blob/main/.github/workflows/maven.yml

name: Render Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render_tests:
    name: Render tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'render-tests/.nvmrc'
    - name: Generate PMTiles
      working-directory: render-tests
      run: ./generate_pmtiles.sh
    - name: Build styles
      run: npm ci && npm run build
      working-directory: styles
    - name: Build render tests
      run: npm ci && npm run build
      working-directory: render-tests
    - name: Run render tests
      run: npm run test
      working-directory: render-tests
    - name: Upload render test results.html on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: render-test-report
        path: ${{ github.workspace }}/render-tests/results.html

